In [10]:
import numpy as np
arr=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr))#same as axis 2
print()
print(np.sort(arr,axis=0))
print()
print(np.sort(arr,axis=1))
print()
print(np.sort(arr,axis=2))

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]

[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]

[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


In [13]:
arr=np.array([1,2,3,4,5])
print(arr+2)
print(arr*2)
print(arr/2)

[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
