# NumPy
-Numerical python
-python library used for working with array
-created in 2005 by Travis Oliphant
-Lists that serves the purpose of arrays but slow to process
-numpy aims to provide one array object that is upto 50x faster than traditional python list.

--syntax: [1 2 3 4 5]

In [5]:
#numpy occupies less space than normal list.(only for knowledge purpose)
import numpy as np
import sys
s=range(1000)
print("size of each element of list in bytes:",sys.getsizeof(s)*len(s))
d=np.arange(1000)
print("size of each element of numpy array in bytes",d.itemsize)
print("size of whole numpy array in bytes",d.itemsize*d.size)

size of each element of list in bytes: 48000
size of each element of numpy array in bytes 4
size of each element of list in bytes 4000


In [10]:
import numpy as np
arr=np.array(42)# here it is 0 nd array
print(arr)
print(arr.ndim)
print(type(arr))

42
0
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5])#here it is 1 ndimension array
print(arr)
print(arr.ndim)
print(type(arr))

[1 2 3 4 5]
1
<class 'numpy.ndarray'>


In [21]:
#2d or higher dimension array should have same size.
import numpy as np
arr=np.array([[1,2,3,4,5],[5,6,7,8,9]])#here it is 2 ndimension array
print(arr)
print(arr.ndim)
print(type(arr))
print(arr[0,1])
print(arr[1,1])
print(arr[0,3])
print(arr[1,2])

[[1 2 3 4 5]
 [5 6 7 8 9]]
2
<class 'numpy.ndarray'>
2
6
4
7


In [19]:
import numpy as np
arr=np.array([[[1,2,3,4,5]]])#no of brackets tell the dimension
print(arr)
print(arr.ndim)
print(type(arr))
print(arr[0][0][0])
print(arr[0][0])
print(arr[0])

[[[1 2 3 4 5]]]
3
<class 'numpy.ndarray'>
1
[1 2 3 4 5]
[[1 2 3 4 5]]


In [31]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,-1])
print(arr[0,-3])
print(arr[1:2,0:3])
print(arr[0:2,2])

8
2
[[5 6 7]]
[3 7]


In [32]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0:2,0:2,0:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [37]:
#shape
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1.ndim)
print(arr1.shape)
print(arr2.ndim)
print(arr2.shape)
print(arr3.ndim)
print(arr3.shape)

1
(5,)
2
(2, 4)
3
(2, 2, 3)


In [39]:
#ndmin
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [52]:
#reshape
import numpy as np
arr1=np.array([1,2,3,4,5,6])
#newarr=arr1.reshape(3,2)
#newarr=arr1.reshape(2,3)
#newarr=arr1.reshape(2,-1)
newarr=arr1.reshape(2,-1).base
# newarr=arr1.reshape(3,-1)
print(newarr)

[1 2 3 4 5 6]


In [55]:
#iteration->no of ndim= no of loops
arr=np.array([[1,2,3,4,5]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5


In [63]:
#nditer
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(arr[:,::1]):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [68]:
#Built in function
#1)concatenate
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3),axis=0)#axis define no of rows and columns |axis-1 error
print(arr)

[1 2 3 4 5 6 7 8 9]


In [75]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
# arr=np.concatenate((arr1,arr2),axis=1)
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [88]:
#2)split
import numpy as np
arr=np.array([1,2,3,4,5])
newarr=np.array_split(arr,3)#(arr,no ofsplits in array)
print(newarr)

[array([1, 2]), array([3, 4]), array([5])]


In [97]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
#newarr=np.array_split(arr,4)
#newarr=np.array_split(arr,3)
newarr=np.array_split(arr,4,axis=1)
print(newarr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [110]:
#3)where
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
#x=np.where(arr==4)
x=np.where(arr%2==0)#by index
print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [111]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
x=np.where(arr==4)
print(x)

(array([1], dtype=int64), array([1], dtype=int64))
